import { RGBA, TextAttributes } from "@opentui/core";

export const colors = {
  accent: RGBA.fromIndex(1),
  error: RGBA.fromHex("#ff6b6b"),
  genderFemale: RGBA.fromHex("#f472b6"),
  genderMale: RGBA.fromHex("#60a5fa"),
  indicatorBlue: RGBA.fromIndex(4),
  indicatorGreen: RGBA.fromIndex(2),
  indicatorRed: RGBA.fromIndex(1),
  indicatorYellow: RGBA.fromIndex(3),
  keyHint: RGBA.fromHex("#ffffff"),
  multiplierDoubleResist: RGBA.fromHex("#8b0000"),
  multiplierImmune: RGBA.fromHex("#4a4a4a"),
  multiplierResist: RGBA.fromHex("#b00000"),
  multiplierText: RGBA.fromHex("#ffff66"),
  multiplierWeak: RGBA.fromHex("#4e9a06"),
  modalBackdrop: RGBA.fromHex("#000000"),
  modalBackground: RGBA.fromHex("#2d2d2d"),
  selected: RGBA.fromIndex(4),
  selectedText: RGBA.fromIndex(0),
  muted: RGBA.fromIndex(7),
  panelOverview: RGBA.fromHex("#2f6f4e"),
  panelSecondary: RGBA.fromHex("#4a4a4a"),
  panelSprite: RGBA.fromHex("#8a8a8a"),
  statEmpty: RGBA.fromHex("#3a3a3a"),
  statHp: RGBA.fromHex("#8ee85d"),
  statAttack: RGBA.fromHex("#f6dd66"),
  statDefense: RGBA.fromHex("#f39a5c"),
  statSpecialAttack: RGBA.fromHex("#62cbe0"),
  statSpecialDefense: RGBA.fromHex("#8296df"),
  statSpeed: RGBA.fromHex("#d95dc3"),
  typeBug: RGBA.fromHex("#a8b820"),
  typeDark: RGBA.fromHex("#705848"),
  typeDragon: RGBA.fromHex("#7038f8"),
  typeElectric: RGBA.fromHex("#f8d030"),
  typeFairy: RGBA.fromHex("#ee99ac"),
  typeFighting: RGBA.fromHex("#c03028"),
  typeFire: RGBA.fromHex("#f08030"),
  typeFlying: RGBA.fromHex("#a890f0"),
  typeGhost: RGBA.fromHex("#705898"),
  typeGrass: RGBA.fromHex("#78c850"),
  typeGround: RGBA.fromHex("#e0c068"),
  typeIce: RGBA.fromHex("#98d8d8"),
  typeNormal: RGBA.fromHex("#a8a878"),
  typePoison: RGBA.fromHex("#a040a0"),
  typePsychic: RGBA.fromHex("#f85888"),
  typeRock: RGBA.fromHex("#b8a038"),
  typeSteel: RGBA.fromHex("#b8b8d0"),
  typeTagTextDark: RGBA.fromHex("#111111"),
  typeTagTextLight: RGBA.fromHex("#ffffff"),
  typeWater: RGBA.fromHex("#6890f0"),
} as const;

export const textStyles = {
  active: TextAttributes.BOLD,
  muted: TextAttributes.NONE,
  normal: TextAttributes.NONE,
  selected: TextAttributes.BOLD,
} as const;
